# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: RunTests
  default: true

trigger: none
pr:
  branches:
    include:
    - main
    - release-*

pool:
    vmImage: 'ubuntu-20.04'
jobs:
- job: RunTests
  timeoutInMinutes: 0
  strategy: 
    maxParallel: 5
    matrix:
      Helm_3_10_3_single: 
        HelmVersion: "3.10.3"
        TestType: single
      Helm_3_10_3_multi: 
        HelmVersion: "3.10.3"
        TestType: multi
      Helm_3_11_0_single: 
        HelmVersion: "3.11.3"
        TestType: single
      Helm_3_11_0_multi: 
        HelmVersion: "3.11.3"
        TestType: multi
      Helm_3_12_3_single: 
        HelmVersion: "3.12.3"  
        TestType: single
      Helm_3_12_3_multi: 
        HelmVersion: "3.12.3"  
        TestType: multi

  steps:
  - template: azure-pipelines-test.yml  # Template reference
    parameters:
      RunTests: ${{ parameters.RunTests }}