# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: RunTests
  default: true

trigger: none
pr: none

pool:
    vmImage: 'ubuntu-20.04'

jobs:
- job: RunTests
  steps:

  - template: azure-pipelines-test.yml  # Template reference
    parameters:
      RunTests: ${{ parameters.RunTests }}
      HelmVersions:
      - version: "3.0.0"
#     - version: "3.0.1"
#     - version: "3.0.2"
      - version: "3.0.3"
      - version: "3.1.0"
      - version: "3.1.1"
      - version: "3.1.2"
      - version: "3.1.3"
      - version: "3.2.0"
      - version: "3.2.1"
      - version: "3.2.2"
      - version: "3.2.3"
      - version: "3.2.4"
      - version: "3.3.0"
      - version: "3.3.1"
      - version: "3.3.2"
      - version: "3.3.3"
      - version: "3.3.4"
      - version: "3.4.0"
      - version: "3.4.1"
      - version: "3.4.2"
      - version: "3.5.0"
      - version: "3.5.1"
      - version: "3.5.2"
    
- job: CreateRelease
  dependsOn: RunTests
  steps:
  
  - script: |
        set -euo pipefail
        echo package chart
        cp -r . $(Agent.TempDirectory)
        cd $(Agent.TempDirectory)
        wget https://github.com/helm/chart-releaser/releases/download/v1.1.1/chart-releaser_1.1.1_linux_amd64.tar.gz
        tar -xvzf chart-releaser_1.1.1_linux_amd64.tar.gz -C ./
        ls
        sudo chmod +x ./cr
        sudo ./cr package ./hull 
        sudo ./cr upload --git-repo hull --owner vidispine --token $(GITHUBTOKEN) || true
        mkdir .cr-index
        wget https://vidispine.github.io/hull/index.yaml -O .cr-index/index.yaml
        sudo ./cr index --git-repo hull --owner vidispine --token $(GITHUBTOKEN) --charts-repo https://vidispine.github.io/hull --push 
