# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: RunTests
  default: true

trigger: none
pr: none

pool:
    vmImage: 'ubuntu-20.04'

jobs:
- job: RunTests
  strategy: 
    maxParallel: 100
    matrix:
      Helm_3_1_1:
        HelmVersion: "3.1.1"
      Helm_3_1_2:
        HelmVersion: "3.1.2"
      Helm_3_1_3:
        HelmVersion: "3.1.3"
      Helm_3_2_0: 
        HelmVersion: "3.2.0"
      Helm_3_2_1: 
        HelmVersion: "3.2.1"
      Helm_3_2_2: 
        HelmVersion: "3.2.2"
      Helm_3_2_3: 
        HelmVersion: "3.2.3"
      Helm_3_2_4: 
        HelmVersion: "3.2.4"
      Helm_3_3_0: 
        HelmVersion: "3.3.0"
      Helm_3_3_1:
        HelmVersion: "3.3.1"
      Helm_3_3_2: 
        HelmVersion: "3.3.2"
      Helm_3_3_3: 
        HelmVersion: "3.3.3"
      Helm_3_3_4: 
        HelmVersion: "3.3.4"
      Helm_3_4_0: 
        HelmVersion: "3.4.0"
      Helm_3_4_1: 
        HelmVersion: "3.4.1"
      Helm_3_4_2: 
        HelmVersion: "3.4.2"
      Helm_3_5_0: 
        HelmVersion: "3.5.0"
      Helm_3_5_1: 
        HelmVersion: "3.5.1"
      Helm_3_5_2: 
        HelmVersion: "3.5.2"
      Helm_3_5_3: 
        HelmVersion: "3.5.3"
      Helm_3_5_4: 
        HelmVersion: "3.5.4"
      Helm_3_6_0: 
        HelmVersion: "3.6.0"
      Helm_3_6_1: 
        HelmVersion: "3.6.1"
      Helm_3_6_2: 
        HelmVersion: "3.6.2"
      Helm_3_6_3: 
        HelmVersion: "3.6.3"
      Helm_3_7_0: 
        HelmVersion: "3.7.0"
      Helm_3_7_1: 
        HelmVersion: "3.7.1"
      Helm_3_7_2: 
        HelmVersion: "3.7.2"
      Helm_3_8_0: 
        HelmVersion: "3.8.0"
      Helm_3_8_1: 
        HelmVersion: "3.8.1"
  
  steps:
  - template: azure-pipelines-test.yml  # Template reference
    parameters:
      RunTests: ${{ parameters.RunTests }}

- job: CreateRelease
  dependsOn: RunTests
  steps:
  
  - script: |
        set -euo pipefail
        echo package chart
        cp -r . $(Agent.TempDirectory)
        cd $(Agent.TempDirectory)
        wget https://github.com/helm/chart-releaser/releases/download/v1.1.1/chart-releaser_1.1.1_linux_amd64.tar.gz
        tar -xvzf chart-releaser_1.1.1_linux_amd64.tar.gz -C ./
        ls
        sudo chmod +x ./cr
        sudo ./cr package ./hull 
        sudo ./cr upload --git-repo hull --owner vidispine --token $(GITHUBTOKEN) || true
        mkdir .cr-index
        wget https://vidispine.github.io/hull/index.yaml -O .cr-index/index.yaml
        sudo ./cr index --git-repo hull --owner vidispine --token $(GITHUBTOKEN) --charts-repo https://vidispine.github.io/hull --push 
