# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: RunTests
  default: true

trigger: none
pr:
  branches:
    include:
    - main
    - release-*

pool:
    vmImage: 'ubuntu-20.04'
jobs:
- job: RunTests
  strategy: 
    maxParallel: 100
    matrix:
      Helm_3_5_4: 
        HelmVersion: "3.5.4"
      Helm_3_6_3: 
        HelmVersion: "3.6.3"
      Helm_3_7_2: 
        HelmVersion: "3.7.2"
      Helm_3_8_2: 
        HelmVersion: "3.8.2"
      Helm_3_9_4: 
        HelmVersion: "3.9.4"
      Helm_3_10_3: 
        HelmVersion: "3.10.3"
      Helm_3_11_0: 
        HelmVersion: "3.11.2"
  steps:
  - template: azure-pipelines-test.yml  # Template reference
    parameters:
      RunTests: ${{ parameters.RunTests }}