# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: HelmVersions
  type: object
  default: []
- name: RunTests
  type: boolean
  default: true

steps:
- script: |
      set -euo pipefail
      echo installing gauge
      sudo curl -SsL https://downloads.gauge.org/stable | sh
      cd hull/files/test/HULL
      sudo pip install -r requirements.txt
      gauge
  displayName: 'install gauge'
  condition: and(gt(length('${{join(' ',parameters.HelmVersions) }}'),0),eq('${{ parameters.RunTests }}','true'))

- ${{ each version in parameters.HelmVersions }}: # Each Helm Version
  
  - script: |
      set -euo pipefail
      echo installing helm
      wget https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      sudo chmod +x ./get-helm-3
      sudo ./get-helm-3 --version v${{ version.version }}
      helm version
    displayName: 'install helm v${{ version.version }}'
    condition: and(gt(length('${{join(' ',parameters.HelmVersions) }}'),0),eq('${{ parameters.RunTests }}','true'))
    
  - script: |
      set -euo pipefail
      echo starting gauge test against helm version `helm version`
      ls
      cd hull/files/test/HULL
      ls
      gauge run -p -l debug specs
    displayName: 'gauge test against helm v${{ version.version }}'
    condition: and(gt(length('${{join(' ',parameters.HelmVersions) }}'),0),eq('${{ parameters.RunTests }}','true'))
